[package]
name = "ranortv-launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = { version = "1.3", default-features = false, features = [
    "std",
    "renderer-gl",
    "accessibility",
] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false }

[build-dependencies]
slint-build = "1.3"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
