// styles/theme.slint
import "../../assets/fonts/RobotoMono-Regular.ttf";
import "../../assets/fonts/RobotoMono-Bold.ttf";
import "../../assets/fonts/Montserrat-Regular.ttf";
import "../../assets/fonts/Montserrat-Bold.ttf";

export global Theme {
    // Colors
    in property <color> color-background: #1a1a2e;
    in property <color> color-surface: #ffffff10;
    in property <color> color-surface-focused: #ffffff20;
    in property <color> color-surface-selected: #ffffff30;
    in property <color> color-text: white;
    in property <color> color-text-muted: #ffffff80;
    in property <color> color-shadow: #00000040;

    // Typography
    in property <length> font-size-title: 32px;
    in property <length> font-size-heading: 24px;
    in property <length> font-size-body: 16px;
    in property <length> font-size-sm: 14px;
    in property <length> font-size-md: 24px;
    in property <length> font-size-lg: 32px;
    in property <length> font-size-xl: 48px;
    out property <string> font-mono: "Montserrat";
    out property <string> font-mono-bold: "Montserrat Bold";


    // Spacing
    in property <length> spacing-xs: 8px;
    in property <length> spacing-sm: 12px;
    in property <length> spacing-md: 20px;
    in property <length> spacing-lg: 40px;
    in property <length> spacing-xl: 80px;

    // Corners
    in property <length> radius-sm: 6px;
    in property <length> radius-md: 8px;
    in property <length> radius-round: 20px;
}
