import { Theme } from "../styles/theme.slint";
import { VerticalBox } from "std-widgets.slint";

export component DateTimeDisplay inherits Rectangle {
    in property <string> date-text;
    in property <string> time-text;
    width: 500px;
    height: 110px;
    VerticalBox {
        alignment: end;
        spacing: 2px;
        padding-right: 30px;
        padding-top: 20px;
        Text {
            text: root.date-text;
            color: Theme.color-text;
            font-size: 48px;
            font-weight: 700;
            font-family: Theme.font-mono-bold;
            horizontal-alignment: right;
        }

        Text {
            text: root.time-text;
            color: rgba(255, 255, 255, 0.8); // Slightly dimmed/different color
            font-size: 32px;
            font-weight: 400;
            font-family: Theme.font-mono;
            horizontal-alignment: right;
        }
    }
}
